trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: pipelineTemplates
      type: github
      endpoint: github-azure-devops-e2e
      name: Azure-DevOps-E2E/devops
      ref: refs/heads/main

variables:
  - group: nexuscart-shared
  - name: vmImage
    value: ubuntu-latest
  - name: serviceName
    value: user-service
  - name: imageRepository
    value: user-service
  - name: dockerfilePath
    value: Dockerfile
  - name: imageTag
    value: $(Build.BuildId)
  - name: fullImageName
    value: $(acrLoginServer)/$(imageRepository):$(imageTag)

extends:
  template: pipelines/templates/pipeline-contract.yml@pipelineTemplates
  parameters:
    pipelineStages:
      - template: pipelines/stages/ci.yml@self
      - template: pipelines/stages/deploy-dev.yml@self
      - template: pipelines/stages/deploy-prod.yml@self
