trigger: none

pr: none

parameters:
- name: releaseTag
  displayName: 'Release Git tag'
  type: string
  default: ''

resources:
  repositories:
  - repository: templates
    type: github
    endpoint: github.com_Azure-DevOps-E2E
    name: Azure-DevOps-E2E/config-management
    ref: refs/heads/main

variables:
- group: nexuscart-shared
- name: serviceName
  value: 'user-service'
- name: imageRepository
  value: 'user-service'

pool:
  name: 'Azure Pipelines'

extends:
  template: pipelines/templates/pipeline-contract.yml@templates
  parameters:
    pipelineStages:
    - template: pipelines/templates/stages/manual-release.yml@templates
      parameters:
        serviceName: 'user-service'
        releaseTag: ${{ parameters.releaseTag }}
