trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: devops
      type: github
      endpoint: github-azure-devops-e2e
      name: Azure-DevOps-E2E/devops
      ref: refs/heads/main

extends:
  template: pipelines/templates/service-pipeline.yml@devops
  parameters:
    serviceName: user-service
    imageRepository: user-service
    dockerfilePath: Dockerfile
    testCommand: |
      go test ./...
